### ISSUE TITLE
Zombie FFMPEG

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/ASM-data-server#18]
Configuration:

- Starting ASM Sensor Node v0.0.0.1, d0decee
- ASM Data Server v0.0.0.1, b3f5e36 dirty
    - Changes are adding `asm_config.yaml`, adding `import DataServer` to `server.py`

Steps to reproduce:

1. Started ASM Data Server on e4e-brix.dynamic.ucsd.edu
2. Started Sensor Node as `ASM_NestingBox` on local PC

Observed behavior:

1. Sensor node starts an RTP session, initializes on port 9101
2. This session times out, Sensor node starts second RTP session on 9102
3. Both FFMPEG sessions are still alive on the server

Desired behavior:
First FFMPEG session should time out so that the port can be reused.

**Comment by ntlhui** [comment]
[asm_server.log](https://github.com/UCSD-E4E/ASM-data-server/files/7577064/asm_server.log)

ASM Server Config:
```
data_dir: /home/asm-data/nas/data
port: 9000
server_uuid: 'fda6297c-1107-11ec-bbd2-fcaa14694a7a'
video_increment: 300
```

ASM Sensor Node Config:
```
# This is a sample configuration file for the Aye-aye Sleep Monitoring Sensor
# Node.  Use this as a basis for configuring the Raspberry Pi for the specific
# deployment environment.

# Device UUID
# 
# This is the UUID that uniquely identifies this device and configuration.
# Nominally, this will be assigned to the device prior to deployment.  This
# should be unique to the device and deployment - that is, if you move a device,
# assign it a new UUID.  This is to keep the device tree identifiable.
uuid: 0579ded8-1116-11ec-a964-54e1ad5146fa

# Device Type
# 
# This is the device type.  Use this field to configure the behavior of the
# device.  See the available options in SensorNode.sensor_nodes.
type: ASM_NestingBox

# Data Server
# 
# This is the location of the data server.  This can either be a domain name
# such as e4e-asm.ucsd.edu, or an IP address such as 192.168.1.77
data_server: e4e-brix.dynamic.ucsd.edu

# Data Server Port
# 
# This is the primary port for the data server.  Refer to the data server
# configuration.
port: 9000

# Data Server UUID
# 
# This is the UUID of the data server.  This is used to ensure that data is
# routed correctly on the data server.  Refer to the data server configuration
# for options.
data_server_uuid: fda6297c-1107-11ec-bbd2-fcaa14694a7a

# Sensor Node Heartbeat
# 
# This is how often the heartbeat packet is sent in seconds.
heartbeat_period_s: 300

ASM_NESTING_BOX:
  video_endpoint: /dev/video2
  illumination_on: '18:00'
  illumination_off: '08:00'
  illumination_level: 90
  illumination_pin: GPIO19
```
[asm_sensor_node.log](https://github.com/UCSD-E4E/ASM-data-server/files/7577071/asm_sensor_node.log)
